# Generated by Django 5.1.4 on 2025-01-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="notes",
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="notes.tag", verbose_name="Теги"
            ),
        ),
    ]
