# Generated by Django 5.1.4 on 2025-01-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_remove_tag_notes_note_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="notes.note",
                    ),
                ),
                (
                    "to_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь между заметками",
                "verbose_name_plural": "Связи между заметками",
            },
        ),
    ]
